services:
  itsm-app:
    container_name: itsm-app-test
    env_file:
      - .env.test
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3001}
      RUN_SEED_ON_START: ${RUN_SEED_ON_START:-false}
    ports:
      - "3001:3000"
    restart: unless-stopped

  postgres:
    container_name: itsm-postgres-test
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    restart: unless-stopped
