"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { MoreHorizontal, Eye, CheckCircle, XCircle, FileText, Edit, Save, X, Globe, Loader2 } from "lucide-react"
import Link from "next/link"
import { updateSuggestion, convertSuggestionToArticle, deleteSuggestion } from "../actions"
import { useRouter } from "next/navigation"

interface Suggestion {
  id: string
  title: string
  targetAudience: string
  problemSummary: string
  draftResolution: string
  status: string
  createdAt: string
  author?: { name?: string; email?: string }
  reviewedBy?: { name?: string; email?: string }
  ticketCluster?: any
  complexityScore?: number | null
  ticketIds?: string
}

interface SuggestionsTableWithDialogProps {
  suggestions: Suggestion[]
  canManageSuggestions: boolean
  canCreateArticles: boolean
  canPublishArticles: boolean
  searchFilter?: string
  statusFilter?: string
  audienceFilter?: string
}

export function SuggestionsTableWithDialog({
  suggestions,
  canManageSuggestions,
  canCreateArticles,
  canPublishArticles,
  searchFilter,
  statusFilter,
  audienceFilter,
}: SuggestionsTableWithDialogProps) {
  const router = useRouter()
  const [selectedSuggestion, setSelectedSuggestion] = useState<Suggestion | null>(null)
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [isEditMode, setIsEditMode] = useState(false)
  const [editedTitle, setEditedTitle] = useState("")
  const [editedProblemSummary, setEditedProblemSummary] = useState("")
  const [editedDraftResolution, setEditedDraftResolution] = useState("")
  const [editedTargetAudience, setEditedTargetAudience] = useState("")
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [activeRowActionId, setActiveRowActionId] = useState<string | null>(null)
  const [pendingStatusAction, setPendingStatusAction] = useState<{
    id: string
    type: "approve" | "decline" | "publish"
    title: string
  } | null>(null)

  // Helper to format date
  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  }

  // Helper to get badge variant for status
  const getStatusBadgeVariant = (status: string) => {
    switch (status) {
      case "PENDING_REVIEW": return "secondary"
      case "APPROVED": return "default"
      case "REJECTED": return "destructive"
      case "PUBLISHED": return "default"
      default: return "outline"
    }
  }

  // Helper to get badge variant for audience
  const getAudienceBadgeVariant = (audience: string) => {
    switch (audience) {
      case "END_USER": return "secondary"
      case "IT_SUPPORT": return "default"
      default: return "outline"
    }
  }

  // Helper to format ticket cluster object
  const formatTicketCluster = (cluster: any): string => {
    if (cluster == null) return '';
    if (typeof cluster === 'string') return cluster;
    if (typeof cluster === 'number' || typeof cluster === 'boolean') return String(cluster);
    if (Array.isArray(cluster)) return cluster.join(', ');
    if (typeof cluster === 'object') {
      try {
        const parts: string[] = [];
        if (cluster.category) parts.push(`Category: ${String(cluster.category)}`);
        if (cluster.generatedBy) parts.push(`Generated by: ${String(cluster.generatedBy)}`);
        if (cluster.commonKeywords && Array.isArray(cluster.commonKeywords)) {
          parts.push(`Keywords: ${cluster.commonKeywords.slice(0, 5).join(', ')}`);
        }
        if (cluster.complexityScore) parts.push(`Complexity: ${String(cluster.complexityScore)}`);
        if (parts.length > 0) return parts.join(', ');
        return JSON.stringify(cluster, null, 2);
      } catch {
        return String(cluster);
      }
    }
    return String(cluster);
  }

  const handleViewDetails = (suggestion: Suggestion) => {
    setSelectedSuggestion(suggestion)
    setEditedTitle(suggestion.title)
    setEditedProblemSummary(suggestion.problemSummary)
    setEditedDraftResolution(suggestion.draftResolution)
    setEditedTargetAudience(suggestion.targetAudience)
    setIsEditMode(false)
    setIsDialogOpen(true)
  }

  const handleCloseDialog = () => {
    setIsDialogOpen(false)
    setSelectedSuggestion(null)
    setIsEditMode(false)
  }

  const handleEditToggle = () => {
    setIsEditMode(!isEditMode)
  }

  const handleOpenEdit = (suggestion: Suggestion) => {
    setSelectedSuggestion(suggestion)
    setEditedTitle(suggestion.title)
    setEditedProblemSummary(suggestion.problemSummary)
    setEditedDraftResolution(suggestion.draftResolution)
    setEditedTargetAudience(suggestion.targetAudience)
    setIsEditMode(true)
    setIsDialogOpen(true)
  }

  const openStatusConfirmDialog = (suggestion: Suggestion, type: "approve" | "decline" | "publish") => {
    setPendingStatusAction({
      id: suggestion.id,
      type,
      title: suggestion.title,
    })
  }

  const handleSaveEdit = async () => {
    if (!selectedSuggestion) return
    setIsSubmitting(true)
    try {
      await updateSuggestion(selectedSuggestion.id, {
        title: editedTitle,
        problemSummary: editedProblemSummary,
        draftResolution: editedDraftResolution,
        targetAudience: editedTargetAudience,
      })
      // Refresh the page to show updated data
      router.refresh()
      setIsEditMode(false)
      // Update local selected suggestion
      setSelectedSuggestion({
        ...selectedSuggestion,
        title: editedTitle,
        problemSummary: editedProblemSummary,
        draftResolution: editedDraftResolution,
        targetAudience: editedTargetAudience,
      })
    } catch (error) {
      console.error("Failed to update suggestion:", error)
      alert("Failed to update suggestion. Please try again.")
    } finally {
      setIsSubmitting(false)
    }
  }

  const handlePublish = async () => {
    if (!selectedSuggestion) return
    setIsSubmitting(true)
    try {
      await convertSuggestionToArticle(selectedSuggestion.id, true)
      router.refresh()
      handleCloseDialog()
    } catch (error) {
      console.error("Failed to publish suggestion:", error)
      alert("Failed to publish suggestion. Please try again.")
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleConvertToArticle = async (publish: boolean) => {
    if (!selectedSuggestion) return
    setIsSubmitting(true)
    try {
      await convertSuggestionToArticle(selectedSuggestion.id, publish)
      router.refresh()
      handleCloseDialog()
    } catch (error) {
      console.error("Failed to convert suggestion:", error)
      alert("Failed to convert suggestion. Please try again.")
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleApprove = async (id: string) => {
    setIsSubmitting(true)
    setActiveRowActionId(id)
    try {
      await updateSuggestion(id, { status: "APPROVED" })
      if (selectedSuggestion?.id === id) {
        setSelectedSuggestion({ ...selectedSuggestion, status: "APPROVED" })
      }
      router.refresh()
    } catch (error) {
      console.error("Failed to approve suggestion:", error)
      alert("Failed to approve suggestion. Please try again.")
    } finally {
      setIsSubmitting(false)
      setActiveRowActionId(null)
    }
  }

  const handleReject = async (id: string) => {
    setIsSubmitting(true)
    setActiveRowActionId(id)
    try {
      await updateSuggestion(id, { status: "REJECTED" })
      if (selectedSuggestion?.id === id) {
        setSelectedSuggestion({ ...selectedSuggestion, status: "REJECTED" })
      }
      router.refresh()
    } catch (error) {
      console.error("Failed to reject suggestion:", error)
      alert("Failed to reject suggestion. Please try again.")
    } finally {
      setIsSubmitting(false)
      setActiveRowActionId(null)
    }
  }

  const handleConfirmStatusAction = async () => {
    if (!pendingStatusAction) return
    if (pendingStatusAction.type === "approve") {
      await handleApprove(pendingStatusAction.id)
    } else if (pendingStatusAction.type === "publish") {
      await handleConvert(pendingStatusAction.id, true)
    } else {
      await handleReject(pendingStatusAction.id)
    }
    setPendingStatusAction(null)
  }

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this suggestion?")) return
    setActiveRowActionId(id)
    try {
      await deleteSuggestion(id)
      router.refresh()
    } catch (error) {
      console.error("Failed to delete suggestion:", error)
      alert("Failed to delete suggestion. Please try again.")
    } finally {
      setActiveRowActionId(null)
    }
  }

  const handleConvert = async (id: string, publish: boolean) => {
    setActiveRowActionId(id)
    try {
      await convertSuggestionToArticle(id, publish)
      router.refresh()
    } catch (error) {
      console.error("Failed to convert suggestion:", error)
      alert("Failed to convert suggestion. Please try again.")
    } finally {
      setActiveRowActionId(null)
    }
  }

  return (
    <>
      {/* Filter and search UI (optional) - can be kept server-side as is */}
      {/* Suggestions Table */}
      {suggestions.length === 0 ? (
        <div className="text-center py-12">
          <FileText className="mx-auto h-12 w-12 text-muted-foreground" />
          <h3 className="mt-4 text-lg font-semibold">No suggestions yet</h3>
          <p className="text-muted-foreground">
            Click 'Generate Suggestions' to analyze tickets and create article drafts.
          </p>
        </div>
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Title</TableHead>
              <TableHead>Audience</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Created</TableHead>
              <TableHead>Author</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {suggestions.map((suggestion) => (
              <TableRow key={suggestion.id}>
                <TableCell className="font-medium">
                  <div 
                    className="max-w-xs truncate cursor-pointer hover:text-primary hover:underline"
                    onClick={() => handleViewDetails(suggestion)}
                  >
                    {suggestion.title}
                  </div>
                  <div className="text-xs text-muted-foreground truncate">
                    {suggestion.problemSummary.substring(0, 60)}...
                  </div>
                </TableCell>
                <TableCell>
                  <Badge variant={getAudienceBadgeVariant(suggestion.targetAudience)}>
                    {suggestion.targetAudience.replace('_', ' ')}
                  </Badge>
                </TableCell>
                <TableCell>
                  <Badge variant={getStatusBadgeVariant(suggestion.status)}>
                    {suggestion.status.replace('_', ' ')}
                  </Badge>
                </TableCell>
                <TableCell>{formatDate(suggestion.createdAt)}</TableCell>
                <TableCell>
                  <div className="text-sm">
                    {suggestion.author?.name || suggestion.author?.email || 'System'}
                  </div>
                </TableCell>
                <TableCell className="text-right">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="sm" disabled={activeRowActionId === suggestion.id}>
                        <MoreHorizontal className="h-4 w-4" />
                        <span className="sr-only">Open menu</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuLabel>Actions</DropdownMenuLabel>
                      <DropdownMenuItem onClick={() => handleViewDetails(suggestion)}>
                        <Eye className="mr-2 h-4 w-4" />
                        View Details
                      </DropdownMenuItem>
                      {canManageSuggestions && suggestion.status !== "PUBLISHED" && (
                        <DropdownMenuItem onClick={() => handleOpenEdit(suggestion)}>
                          <Edit className="mr-2 h-4 w-4" />
                          Edit
                        </DropdownMenuItem>
                      )}
                      {canManageSuggestions && suggestion.status === "PENDING_REVIEW" && (
                        <>
                          <DropdownMenuItem onClick={() => openStatusConfirmDialog(suggestion, "approve")} disabled={activeRowActionId === suggestion.id}>
                            {activeRowActionId === suggestion.id ? (
                              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            ) : (
                              <CheckCircle className="mr-2 h-4 w-4" />
                            )}
                            Approve
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => openStatusConfirmDialog(suggestion, "decline")} disabled={activeRowActionId === suggestion.id}>
                            {activeRowActionId === suggestion.id ? (
                              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            ) : (
                              <XCircle className="mr-2 h-4 w-4" />
                            )}
                            Decline
                          </DropdownMenuItem>
                        </>
                      )}
                      {canManageSuggestions && suggestion.status === "REJECTED" && (
                        <>
                          <DropdownMenuItem onClick={() => openStatusConfirmDialog(suggestion, "approve")} disabled={activeRowActionId === suggestion.id}>
                            {activeRowActionId === suggestion.id ? (
                              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            ) : (
                              <CheckCircle className="mr-2 h-4 w-4" />
                            )}
                            Approve
                          </DropdownMenuItem>
                        </>
                      )}
                      {canCreateArticles && suggestion.status === "APPROVED" && (
                        <DropdownMenuItem onClick={() => handleConvert(suggestion.id, false)} disabled={activeRowActionId === suggestion.id}>
                          <FileText className="mr-2 h-4 w-4" />
                          Convert to Article (Draft)
                        </DropdownMenuItem>
                      )}
                      {canPublishArticles && suggestion.status === "APPROVED" && (
                        <DropdownMenuItem onClick={() => openStatusConfirmDialog(suggestion, "publish")} disabled={activeRowActionId === suggestion.id}>
                          <Globe className="mr-2 h-4 w-4" />
                          Publish Article
                        </DropdownMenuItem>
                      )}
                      {canManageSuggestions && suggestion.status !== "PUBLISHED" && (
                        <>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem onClick={() => handleDelete(suggestion.id)} className="text-destructive" disabled={activeRowActionId === suggestion.id}>
                            <XCircle className="mr-2 h-4 w-4" />
                            Delete
                          </DropdownMenuItem>
                        </>
                      )}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}

      {/* Dialog for suggestion details */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Suggestion Details</DialogTitle>
            <DialogDescription>
              Review and manage this AI-generated suggestion.
            </DialogDescription>
          </DialogHeader>

          {selectedSuggestion && (
            <div className="space-y-4">
              {/* Title */}
              <div className="space-y-2">
                <Label htmlFor="title">Title</Label>
                {isEditMode ? (
                  <Input
                    id="title"
                    value={editedTitle}
                    onChange={(e) => setEditedTitle(e.target.value)}
                    disabled={isSubmitting}
                  />
                ) : (
                  <div className="rounded-md border px-3 py-2 text-sm">{selectedSuggestion.title}</div>
                )}
              </div>

              {/* Target Audience */}
              <div className="space-y-2">
                <Label htmlFor="audience">Target Audience</Label>
                {isEditMode ? (
                  <Select value={editedTargetAudience} onValueChange={setEditedTargetAudience} disabled={isSubmitting}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select audience" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="END_USER">End User</SelectItem>
                      <SelectItem value="IT_SUPPORT">IT Support</SelectItem>
                    </SelectContent>
                  </Select>
                ) : (
                  <Badge variant={getAudienceBadgeVariant(selectedSuggestion.targetAudience)}>
                    {selectedSuggestion.targetAudience.replace('_', ' ')}
                  </Badge>
                )}
              </div>

              {/* Status */}
              <div className="space-y-2">
                <Label>Status</Label>
                <Badge variant={getStatusBadgeVariant(selectedSuggestion.status)}>
                  {selectedSuggestion.status.replace('_', ' ')}
                </Badge>
              </div>

              {/* Problem Summary */}
              <div className="space-y-2">
                <Label htmlFor="problemSummary">Problem Summary</Label>
                {isEditMode ? (
                  <Textarea
                    id="problemSummary"
                    value={editedProblemSummary}
                    onChange={(e) => setEditedProblemSummary(e.target.value)}
                    rows={4}
                    disabled={isSubmitting}
                  />
                ) : (
                  <div className="rounded-md border px-3 py-2 text-sm whitespace-pre-line">
                    {selectedSuggestion.problemSummary}
                  </div>
                )}
              </div>

              {/* Draft Resolution */}
              <div className="space-y-2">
                <Label htmlFor="draftResolution">Draft Resolution</Label>
                {isEditMode ? (
                  <Textarea
                    id="draftResolution"
                    value={editedDraftResolution}
                    onChange={(e) => setEditedDraftResolution(e.target.value)}
                    rows={6}
                    disabled={isSubmitting}
                  />
                ) : (
                  <div className="rounded-md border px-3 py-2 text-sm whitespace-pre-line">
                    {selectedSuggestion.draftResolution}
                  </div>
                )}
              </div>

              {/* Metadata */}
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <Label>Created</Label>
                  <div>{formatDate(selectedSuggestion.createdAt)}</div>
                </div>
                <div>
                  <Label>Author</Label>
                  <div>{selectedSuggestion.author?.name || selectedSuggestion.author?.email || 'System'}</div>
                </div>
                {selectedSuggestion.reviewedBy && (
                  <div>
                    <Label>Reviewed By</Label>
                    <div>{selectedSuggestion.reviewedBy.name || selectedSuggestion.reviewedBy.email}</div>
                  </div>
                )}
                {selectedSuggestion.ticketCluster && (
                  <div>
                    <Label>Ticket Cluster</Label>
                    <div>{formatTicketCluster(selectedSuggestion.ticketCluster)}</div>
                  </div>
                )}
                {selectedSuggestion.complexityScore !== null && (
                  <div>
                    <Label>Complexity Score</Label>
                    <div>{selectedSuggestion.complexityScore}</div>
                  </div>
                )}
              </div>

              {/* Action Buttons */}
              <DialogFooter className="flex flex-col sm:flex-row gap-2 pt-4">
                {isEditMode ? (
                  <>
                    <Button variant="outline" onClick={handleEditToggle} disabled={isSubmitting}>
                      <X className="mr-2 h-4 w-4" />
                      Cancel
                    </Button>
                    <Button onClick={handleSaveEdit} disabled={isSubmitting}>
                      <Save className="mr-2 h-4 w-4" />
                      {isSubmitting ? "Saving..." : "Save Changes"}
                    </Button>
                  </>
                ) : (
                  <>
                    {canManageSuggestions && selectedSuggestion.status !== "PUBLISHED" && (
                      <Button variant="outline" onClick={handleEditToggle} disabled={isSubmitting}>
                        <Edit className="mr-2 h-4 w-4" />
                        Edit
                      </Button>
                    )}
                    {canManageSuggestions && selectedSuggestion.status === "PENDING_REVIEW" && (
                      <>
                        <Button
                          variant="default"
                          onClick={() => openStatusConfirmDialog(selectedSuggestion, "approve")}
                          disabled={isSubmitting}
                        >
                          <CheckCircle className="mr-2 h-4 w-4" />
                          {isSubmitting ? "Approving..." : "Approve"}
                        </Button>
                        <Button
                          variant="destructive"
                          onClick={() => openStatusConfirmDialog(selectedSuggestion, "decline")}
                          disabled={isSubmitting}
                        >
                          <XCircle className="mr-2 h-4 w-4" />
                          {isSubmitting ? "Declining..." : "Decline"}
                        </Button>
                      </>
                    )}
                    {canCreateArticles && selectedSuggestion.status === "APPROVED" && !canPublishArticles && (
                      <Button variant="secondary" onClick={() => handleConvertToArticle(false)} disabled={isSubmitting}>
                        <FileText className="mr-2 h-4 w-4" />
                        {isSubmitting ? "Converting..." : "Convert to Article (Draft)"}
                      </Button>
                    )}
                    {canPublishArticles && selectedSuggestion.status === "APPROVED" && (
                      <Button onClick={() => openStatusConfirmDialog(selectedSuggestion, "publish")} disabled={isSubmitting}>
                        <Globe className="mr-2 h-4 w-4" />
                        {isSubmitting ? "Publishing..." : "Publish Article"}
                      </Button>
                    )}
                  </>
                )}
              </DialogFooter>
            </div>
          )}
        </DialogContent>
      </Dialog>

      <Dialog open={pendingStatusAction !== null} onOpenChange={(open) => !open && setPendingStatusAction(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>
              {pendingStatusAction?.type === "approve"
                ? "Approve Suggestion"
                : pendingStatusAction?.type === "publish"
                  ? "Publish Article"
                  : "Decline Suggestion"}
            </DialogTitle>
            <DialogDescription>
              {pendingStatusAction?.type === "approve"
                ? `Are you sure you want to approve "${pendingStatusAction?.title}"?`
                : pendingStatusAction?.type === "publish"
                  ? `Are you sure you want to publish "${pendingStatusAction?.title}" as an article?`
                : `Are you sure you want to decline "${pendingStatusAction?.title}"?`}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setPendingStatusAction(null)}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button
              variant={
                pendingStatusAction?.type === "decline"
                  ? "destructive"
                  : "default"
              }
              onClick={handleConfirmStatusAction}
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Processing...
                </>
              ) : pendingStatusAction?.type === "approve" ? (
                "Confirm Approve"
              ) : pendingStatusAction?.type === "publish" ? (
                "Confirm Publish"
              ) : (
                "Confirm Decline"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}